#!/usr/bin/env Rscript

# do not commit to main branch
if (requireNamespace("gert") && identical (gert::git_branch(), "main"))
    stop ("'main' branch is protected; commits must be made via PR from other branch")